Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.display import Audio

fna = eventname+"_template_whiten.wav"
print(fna)
Audio(fna)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[17], line 5[0m
[1;32m      3[0m fna [38;5;241m=[39m eventname[38;5;241m+[39m[38;5;124m"[39m[38;5;124m_template_whiten.wav[39m[38;5;124m"[39m
[1;32m      4[0m [38;5;28mprint[39m(fna)
[0;32m----> 5[0m [43mAudio[49m[43m([49m[43mfna[49m[43m)[49m

File [0;32m~/envs/ligo/lib/python3.9/site-packages/IPython/lib/display.py:129[0m, in [0;36mAudio.__init__[0;34m(self, data, filename, url, embed, rate, autoplay, normalize, element_id)[0m
[1;32m    127[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mdata [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mdata, [38;5;28mbytes[39m):
[1;32m    128[0m     [38;5;28;01mif[39;00m rate [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 129[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mrate must be specified when data is a numpy array or list of audio samples.[39m[38;5;124m"[39m)
[1;32m    130[0m     [38;5;28mself[39m[38;5;241m.[39mdata [38;5;241m=[39m Audio[38;5;241m.[39m_make_wav(data, rate, normalize)

[0;31mValueError[0m: rate must be specified when data is a numpy array or list of audio samples.
ValueError: rate must be specified when data is a numpy array or list of audio samples.

